Repository SiliconSloth/Metro, pull requests merged in 2020-04, with the labels that each got.

#28 User experience: Second Iteration
  include/commands.h
  include/error.h
  include/gitwrapper/repository.h
  include/helper.h
  include/main.h
  include/metro/syncing.h
  include/pch.h
  src/commands/clone.cpp
  src/commands/delete.cpp
  src/commands/list.cpp
  src/commands/sink.cpp
  src/commands/sync.cpp
  src/gitwrapper/repository.cpp
  src/helper.cpp
  src/main.cpp
  src/metro/credentials.cpp
  src/metro/syncing.cpp
  src/pch.cpp
Labels: enhancement

#34 Fix #21
  include/exit.h
  include/pch.h
  src/commands/clone.cpp
  src/exit.cpp
  src/main.cpp
  src/metro/syncing.cpp
  src/pch.cpp
Labels: bug

#36 Fix #19
  include/error.h
  src/gitwrapper/repository.cpp
Labels: bug

#47 Sync
  include/gitwrapper/branch.h
  include/metro/syncing.h
  src/gitwrapper/branch.cpp
  src/metro/syncing.cpp
Labels: enhancement

#66 Fix #48
  include/error.h
  src/metro/metro.cpp
Labels: bug

#65 Fix #53
  src/commands/clone.cpp
Labels: bug

#64 Fix #63
  include/error.h
  include/helper.h
  src/commands/sink.cpp
  src/helper.cpp
  src/main.cpp
Labels: bug

#69 Add Command Suggestions for Common Git Commands
  include/main.h
  src/main.cpp
Labels: enhancement

#68 Add branches to commit listing
  include/helper.h
  src/commands/list.cpp
  src/helper.cpp
Labels: enhancement

#70 Prevent patch with invalid creds without force
  include/commands.h
  src/commands/patch.cpp
Labels: enhancement

#72 Error messages for switching to current branch
  src/commands/switch.cpp
Labels: enhancement

#73 Automatically switch branch on create
  src/commands/branch.cpp
Labels: enhancement

#75 Add -v option
  include/commands.h
  include/main.h
  src/main.cpp
Labels: enhancement

#78 Implement Rename Command
  include/gitwrapper/branch.h
  include/main.h
  src/commands/rename.cpp
  src/gitwrapper/branch.cpp
  src/pch.cpp
Labels: command
